export interface PrebuiltCreator {
  name: string;
  username: string;
  belt: "BLACK" | "BROWN" | "PURPLE" | "BLUE" | "WHITE";
  bio: string;
  specialties: string[];
  socialInstagram?: string;
  socialYoutube?: string;
  socialTwitter?: string;
  templateId: string;
  status: "claimed_pending";
}

export const BJJ_FANATICS_CREATORS: PrebuiltCreator[] = [
  {
    name: "Gordon Ryan",
    username: "gordonryan",
    belt: "BLACK",
    bio: "The greatest no-gi grappler of all time. Multiple-time ADCC champion and submission specialist known for systematic bodylock passing and devastating back attacks.",
    specialties: ["No-Gi", "Body Lock Passing", "Back Attacks", "Mount Attacks"],
    socialInstagram: "gordonlovesjiujitsu",
    socialYoutube: "GordonRyan",
    socialTwitter: "gordonlovesbjj",
    templateId: "DARK_PRO",
    status: "claimed_pending",
  },
  {
    name: "John Danaher",
    username: "johndanaher",
    belt: "BLACK",
    bio: "Legendary BJJ coach and philosopher of grappling. Creator of the Danaher Death Squad and architect of systematic submission grappling methodology.",
    specialties: ["Leg Locks", "Systems-Based Coaching", "Back Attacks", "Escapes"],
    socialInstagram: "daaborhsoj",
    socialYoutube: "JohnDanaher",
    templateId: "DARK_PRO",
    status: "claimed_pending",
  },
  {
    name: "Craig Jones",
    username: "craigjones",
    belt: "BLACK",
    bio: "Australian grappling sensation known for his devastating leg lock game and irreverent personality. ADCC medalist and one of the most entertaining figures in competitive BJJ.",
    specialties: ["Leg Locks", "No-Gi", "Z-Guard", "Heel Hooks"],
    socialInstagram: "craaborhsoj",
    socialYoutube: "CraigJones",
    socialTwitter: "craborhsoj",
    templateId: "BOLD_SPORT",
    status: "claimed_pending",
  },
  {
    name: "Lachlan Giles",
    username: "lachlangiles",
    belt: "BLACK",
    bio: "ADCC medalist and head coach of Absolute MMA. Known for methodical teaching style and his legendary 2019 ADCC run submitting multiple bigger opponents with heel hooks.",
    specialties: ["Leg Locks", "Half Guard", "No-Gi", "Coaching Methodology"],
    socialInstagram: "lacaborhsoj_giles",
    socialYoutube: "LachlanGiles",
    templateId: "LIGHT_CLEAN",
    status: "claimed_pending",
  },
  {
    name: "Bernardo Faria",
    username: "bernardofaria",
    belt: "BLACK",
    bio: "5x World Champion and the king of the over-under pass. Known as one of the nicest people in BJJ and a prolific instructor with a passion for deep half guard.",
    specialties: ["Over-Under Pass", "Deep Half Guard", "Pressure Passing", "Competition"],
    socialInstagram: "bernardofariabjj",
    socialYoutube: "BernardoFaria",
    templateId: "LIGHT_CLEAN",
    status: "claimed_pending",
  },
  {
    name: "Andre Galvao",
    username: "andregalvao",
    belt: "BLACK",
    bio: "Multiple-time ADCC and IBJJF World Champion. One of the most decorated grapplers in history and founder of Atos Jiu-Jitsu, producing world champions at every belt level.",
    specialties: ["Competition Strategy", "Guard Passing", "Dynamic Guard", "Wrestling"],
    socialInstagram: "andraborhsojvao",
    socialYoutube: "AndreGalvao",
    templateId: "BOLD_SPORT",
    status: "claimed_pending",
  },
  {
    name: "Marcelo Garcia",
    username: "marcelogarcia",
    belt: "BLACK",
    bio: "Widely considered the greatest pound-for-pound grappler ever. 5x World Champion, 4x ADCC Champion. Famous for his butterfly guard, X-guard, and guillotine choke.",
    specialties: ["Butterfly Guard", "X-Guard", "Guillotine", "North-South Choke"],
    socialInstagram: "marcelaborhsojcia",
    socialYoutube: "MarceloGarcia",
    templateId: "DARK_PRO",
    status: "claimed_pending",
  },
  {
    name: "Roger Gracie",
    username: "rogergracie",
    belt: "BLACK",
    bio: "10x World Champion and the most dominant competitor in BJJ history. Known for making fundamental techniques work at the highest level — cross collar choke from mount is his signature.",
    specialties: ["Mount", "Cross Collar Choke", "Fundamentals", "Closed Guard"],
    socialInstagram: "rogergracie",
    socialYoutube: "RogerGracie",
    templateId: "DARK_PRO",
    status: "claimed_pending",
  },
  {
    name: "Caio Terra",
    username: "caioterra",
    belt: "BLACK",
    bio: "12x World Champion and one of the most technical lightweights ever. Known for his innovative guard game and detail-oriented teaching style.",
    specialties: ["Light Featherweight", "Modern Half Guard", "Guard Retention", "Worm Guard"],
    socialInstagram: "caaborhsjjra",
    socialYoutube: "CaioTerra",
    templateId: "LIGHT_CLEAN",
    status: "claimed_pending",
  },
  {
    name: "Tom DeBlass",
    username: "tomdeblass",
    belt: "BLACK",
    bio: "ADCC veteran, UFC fighter, and beloved coach. Known for his half guard mastery and motivational approach to teaching. Head instructor at Ocean County BJJ.",
    specialties: ["Half Guard", "Butterfly Guard", "Self-Defense", "MMA Grappling"],
    socialInstagram: "tomdeblass",
    socialYoutube: "TomDeBlass",
    socialTwitter: "TomDeBlass",
    templateId: "DARK_PRO",
    status: "claimed_pending",
  },
  {
    name: "Garry Tonon",
    username: "garrytonon",
    belt: "BLACK",
    bio: "EBI champion, ADCC medalist, and ONE Championship MMA fighter. A pioneer of modern leg lock systems and one of the original Danaher Death Squad members.",
    specialties: ["Leg Locks", "No-Gi", "MMA Grappling", "Darce Choke"],
    socialInstagram: "garaborhsonon",
    socialYoutube: "GarryTonon",
    templateId: "BOLD_SPORT",
    status: "claimed_pending",
  },
  {
    name: "Eddie Cummings",
    username: "eddiecummings",
    belt: "BLACK",
    bio: "The Wolverine. Original Danaher Death Squad member and pioneer of the modern heel hook game in competitive submission grappling.",
    specialties: ["Heel Hooks", "Ashi Garami", "Leg Entanglements", "No-Gi"],
    socialInstagram: "eddiecummings",
    templateId: "DARK_PRO",
    status: "claimed_pending",
  },
  {
    name: "Nick Rodriguez",
    username: "nickrodriguez",
    belt: "BROWN",
    bio: "ADCC silver medalist who burst onto the grappling scene with incredible athleticism and wrestling-based grappling. Known for explosive takedowns and bodylock pressure.",
    specialties: ["Wrestling", "Body Lock", "Explosive Takedowns", "No-Gi"],
    socialInstagram: "nickaborhsjguez",
    socialYoutube: "NickRodriguez",
    templateId: "BOLD_SPORT",
    status: "claimed_pending",
  },
  {
    name: "Nicky Ryan",
    username: "nickyryan",
    belt: "BLACK",
    bio: "Prodigy of the Danaher system and younger brother of Gordon Ryan. Known for his technical precision and rapidly evolving game in no-gi competition.",
    specialties: ["No-Gi", "Leg Locks", "Back Takes", "Guard Passing"],
    socialInstagram: "nickaborhsjan",
    socialYoutube: "NickyRyan",
    templateId: "DARK_PRO",
    status: "claimed_pending",
  },
  {
    name: "Jay Rodriguez",
    username: "jayrodriguez",
    belt: "BLACK",
    bio: "Rising star in the competitive grappling scene. Known for aggressive submission hunting and dynamic transitions between positions.",
    specialties: ["Submissions", "Transitions", "No-Gi", "Competition"],
    socialInstagram: "jayaborhsjguez",
    templateId: "BOLD_SPORT",
    status: "claimed_pending",
  },
];
